server:
  port: 8088

spring:
  # Redis 配置
  data:
    redis:
      # Redis 服务器地址
      host: localhost
      # Redis 服务器端口
      port: 6379
      # 连接密码 (如果没设置了密码)
      password:
      # 连接超时时间（毫秒）
      timeout: 5000ms
      # 数据库索引 (0-15，默认为0)
      database: 0
      # 连接池配置（使用 Lettuce）
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（负数表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
          # 空闲连接检测周期
          time-between-eviction-runs: 60s

wgy:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSId: 2c94811c9860a9c401991e3a59a520ae
      accountToken: 0cb3e11897dd415091a95895b8ca0559
      appId: 2c94811c9860a9c401991e3a5b0920b5
      templateId: 1