# 1. 邮件发送配置（以QQ邮箱为例，需开启SMTP服务并获取授权码）
spring:
  mail:
    host: smtp.qq.com
    port: 587
    username: 1217663021@qq.com  # 发送方邮箱
    password: mmmdjchuwwfnjdij  # QQ邮箱SMTP授权码（不是登录密码）
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
# 2. 天气API配置（使用「和风天气」免费API，需自行注册获取key）
weather:
  api:
    key: f70f4ea42aae40a28ac06c2c4f716520 # 和风天气API密钥，前面已申请并复制
    city: 101190101					  # 南京的城市ID（可查和风天气城市列表）
    url: https://nx5vxmj8ek.re.qweatherapi.com/v7/weather/3d
# 3. 接收邮件列表
email:
  recipients: 1217663021@qq.com  # 多个收件人用逗号分隔


# 数据库备份配置
db:
  backup:
    host: localhost          # 数据库地址
    port: 3306               # 数据库端口s
    username: root           # 数据库用户名
    password: 123456         # 数据库密码
    db-name: my_mp_test     # 需要备份的数据库名
    local-path: ./db-backup/ # 本地备份文件存储路径


# 健康检查阈值配置
server:
  monitor:
    cpu-threshold: 80.0  # CPU使用率阈值（%）
    memory-threshold: 50.0  # 内存使用率阈值（%），根据自己情况调整，以触发阈值